/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppAdvantageItem: typeof import('./components/AppAdvantageItem.vue')['default']
    AppCarousel: typeof import('./components/AppCarousel.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    AppMainImage: typeof import('./components/AppMainImage.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Medal: typeof import('./components/icons/Medal.vue')['default']
    Money: typeof import('./components/icons/Money.vue')['default']
    Phone: typeof import('./components/icons/Phone.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shield: typeof import('./components/icons/Shield.vue')['default']
  }
}
